# Generated by Django 4.2 on 2025-06-08 09:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('short_description', models.TextField(blank=True, verbose_name='краткое описание')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='полное описание')),
                ('lng', models.FloatField(verbose_name='долгота')),
                ('lat', models.FloatField(verbose_name='широта')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'unique_together': {('title', 'lng', 'lat')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='фотография')),
                ('ordinal_number', models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядковый номер')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='место')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['ordinal_number'],
            },
        ),
    ]
